controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    controller: App\Controller\HomeController:home
    path: /
    stateless: true
